### ISSUE TITLE
infrabox push not working

### ISSUE THREAD

**Issue by vasu1124** [InfraBox/cli#20]
Getting an error while pushing to infrabox.ninja, using INFRABOX_URL="https://infrabox.ninja/api/cli". Token should be correct. Am on Mac.

```
$ infrabox push --show-console
[infrabox] compressing /Users/home/go/src/github.com/vasu1124/introspect
[infrabox] Using .dockerignore
[infrabox] finished, file size is 632.7158203125 kb
[infrabox] Uploading ...
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.13.6</center>
</body>
</html>

Traceback (most recent call last):
  File "/usr/local/bin/infrabox", line 3, in <module>
    infraboxcli.main()
  File "/usr/local/lib/python3.6/site-packages/infraboxcli/__init__.py", line 141, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/infraboxcli/push.py", line 100, in push
    result = upload_zip(args, zip_file)
  File "/usr/local/lib/python3.6/site-packages/infraboxcli/push.py", line 72, in upload_zip
    d = r.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ib-steffen** [comment]
please use `INFRABOX_URL=https://infrabox.ninja`. Did you find the wrong value somewhere in the documentation?

**Comment by vasu1124** [comment]
I think you already fixed the docu at https://github.com/infrabox/cli#push-a-job ... update the ref link under https://infrabox.ninja/docs/#create-auth-token as well (see push workflows).

Will retry my job tmrw and let you know.
